site_name: Documentation CPGEOM 25-27
site_description: Centre de ressources techniques spécialisé en géomatique et systèmes d'information géographique
site_author: Tristan

# Repository
repo_name: cpgeom_doc
repo_url: https://github.com/votre-utilisateur/cpgeom_doc

theme:
  name: material
  language: fr
  palette:
    - scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Mode Matrix
    - scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/brightness-7
        name: Mode Normal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  font:
    text: Roboto Mono
    code: Roboto Mono

extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js

extra_css:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css

nav:
  - Accueil: index.md
  - Introduction:
    - page1.md
  - Sources de données:
    - page2.md
    - page2.1.md
  - Méthodologie:
    - page3.md
  - Qualité:
    - page4.md
  - Interopérabilité et métadonnées:
    - page5.md
  - VRT:
    - page7.md
  - OGR/GDAL:
    - page8.md
  - Base de données:
    - page9.md
